// Mundo 2/Nivel 5/MongoDB/clientes/livros-next/pages/LivroLista.tsx
import 'bootstrap/dist/css/bootstrap.css';
import { useState, useEffect } from 'react';
import styles from '../styles/index.module.css';
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import LinhaLivro from '../componentes/LinhaLivro';
import ControleLivros from '../classes/controle/ControleLivros';
import Livro from '../classes/modelo/Livro';

const LivroLista: React.FC = () => {
  const controleLivros = new ControleLivros();

  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const livros = await controleLivros.obterLivros();
        setLivros(livros);
        setCarregado(true);
      } catch (error) {
        console.error('Erro ao obter livros:', error);
      }
    };
    fetchData();
  }, [carregado]);

  const excluir = (codigo: string) => {
    controleLivros
      .excluir(codigo)
      .then(() => {
        setCarregado(false);
      })
      .catch((error) => {
        console.error('Erro ao excluir livro:', error);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Catálogo de Livros</title>
      </Head>
      <Menu />
      <main className="container">
        <h1>Catálogo de Livros</h1>
        <table className="table table-striped table-borderless table-sm text-left">
          <thead className="table-dark table-sm">
            <tr>
              <th className="col-2">Título</th>
              <th className="col-6">Resumo</th>
              <th className="col-2">Editora</th>
              <th className="col-2">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro key={index} livro={livro} excluir={excluir} />
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// Mundo 2/Nivel 4/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir(codigo: number): void {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container p-3">
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table table-striped table-borderless table-sm text-left">
      <tr class="table btn-dark">
        <th class="col-2">Título</th>
        <th class="col-6">Resumo</th>
        <th class="col-2">Editora</th>
        <th class="col-2">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }} <br>
          <button (click)="excluir(livro.codigo)" class="btn btn-danger">Excluir</button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
