// Mundo 2/Nivel 4/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro(0, 0, '', '', []);
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n').filter(author => author.trim() !== '');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container p-3">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()">
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" name="titulo" [(ngModel)]="livro.titulo" required>
    </div>

    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" required></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora</label>
      <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
        <option selected disabled>Selecione uma Editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="autores">Autores (1 por linha)</label>
      <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Incluir Livro</button>
  </form>
</main>

// Mundo 2/Nivel 5/MongoDB/clientes/livros-next/pages/LivroDados.tsx
import 'bootstrap/dist/css/bootstrap.css';
import styles from '../styles/index.module.css';
import Head from 'next/head';
import { useState, ChangeEvent, FormEvent } from 'react';
import { useRouter } from 'next/router';
import ControleEditora from '../classes/controle/ControleEditora';
import ControleLivros from '../classes/controle/ControleLivros';
import { Menu } from '../componentes/Menu';
import Livro from '../classes/modelo/Livro';
import Editora from '../classes/modelo/Editora';

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivros(); // instância de ControleLivros

const LivroDados = () => {
  const router = useRouter();

  const opcoes: { value: number; text: string }[] = controleEditora.getEditoras().map((editora: Editora) => ({ value: editora.codEditora, text: editora.nome }));

  const [titulo, setTitulo] = useState<string>('');
  const [resumo, setResumo] = useState<string>('');
  const [autores, setAutores] = useState<string>('');
  const [codEditora, setCodEditora] = useState<number>(opcoes[0].value);

  const tratarCombo = (evento: ChangeEvent<HTMLSelectElement>) => {
    const selectedValue = parseInt(evento.target.value, 10);
    setCodEditora(selectedValue);
  };

  const incluir = (evento: FormEvent) => {
    evento.preventDefault();
    const novoLivro: Livro = {
      codigo: '', // utilizar texto vazio para código
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora,
    };
    controleLivros.incluir(novoLivro)
      .then((sucesso) => {
        if (sucesso) {
          router.push('/LivroLista');
        } else {
          console.error('Erro ao incluir o livro.');
        }
      })
      .catch((error) => {
        console.error('Ocorreu um erro ao processar a solicitação.', error);
      });
  };

  return (

    <div className={styles.container}>
      <Head>
        <title>Dados do Livro</title>
      </Head>
      <Menu />
      <main className="container">
        <h1>Dados do Livro</h1>
        <form onSubmit={incluir}>
          <div className="mb-3">
            <label htmlFor="titulo" className="form-label"> Título </label>
            <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} required />
          </div>
          <div className="mb-3">
            <label htmlFor="resumo" className="form-label"> Resumo </label>
            <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)} required />
          </div>
          <div className="mb-3">
            <label htmlFor="editora" className="form-label"> Editora </label>
            <select id="editora" className="form-control form-select" value={codEditora} onChange={tratarCombo}>{opcoes.map((opcao) => (<option key={opcao.value} value={opcao.value}>{opcao.text}</option>))}
            </select> 
          </div>
          <div className="mb-3">
            <label htmlFor="autores" className="form-label"> Autores (1 por linha) </label>
            <textarea className="form-control" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)} required />
          </div>
          <button type="submit" className="btn btn-primary"> Salvar Dados </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;
